import abc
import pandas as pd
from typing import Dict, Any, List, Optional

from bot_core.logger import get_logger
from bot_core.config import StrategyConfig
from bot_core.ai.ensemble_learner import EnsembleLearner
from bot_core.ai.regime_detector import MarketRegimeDetector
from bot_core.position_manager import Position

logger = get_logger(__name__)

class TradingStrategy(abc.ABC):
    """Abstract Base Class for all trading strategies."""
    def __init__(self, config: StrategyConfig):
        self.config = config
        self.symbol = config.symbol

    @abc.abstractmethod
    async def analyze_market(self, df: pd.DataFrame, open_positions: List[Position]) -> Optional[Dict[str, Any]]:
        """Analyzes market data and returns a trading signal."""
        pass

class SimpleMACrossoverStrategy(TradingStrategy):
    """A simple strategy based on the crossover of two moving averages."""
    def __init__(self, config: StrategyConfig):
        super().__init__(config)
        self.fast_ma_period = config.simple_ma.fast_ma_period
        self.slow_ma_period = config.simple_ma.slow_ma_period
        logger.info("SimpleMACrossoverStrategy initialized.")

    async def analyze_market(self, df: pd.DataFrame, open_positions: List[Position]) -> Optional[Dict[str, Any]]:
        if 'sma_fast' not in df.columns or 'sma_slow' not in df.columns:
            logger.warning("Required moving average columns not in DataFrame.")
            return None

        last_row = df.iloc[-1]
        prev_row = df.iloc[-2]
        position_open = any(p.symbol == self.symbol for p in open_positions)

        # Buy signal: fast MA crosses above slow MA
        if not position_open and last_row['sma_fast'] > last_row['sma_slow'] and prev_row['sma_fast'] <= prev_row['sma_slow']:
            logger.info("BUY signal generated by SimpleMACrossoverStrategy", symbol=self.symbol)
            return {'action': 'BUY', 'symbol': self.symbol, 'reason': 'MA Crossover'}

        # Sell signal: fast MA crosses below slow MA
        if position_open and last_row['sma_fast'] < last_row['sma_slow'] and prev_row['sma_fast'] >= prev_row['sma_slow']:
            logger.info("SELL signal generated by SimpleMACrossoverStrategy", symbol=self.symbol)
            return {'action': 'SELL', 'symbol': self.symbol, 'reason': 'MA Crossover'}
        
        return None

class AIEnsembleStrategy(TradingStrategy):
    """An advanced strategy using an ensemble of ML models and market regime detection."""
    def __init__(self, config: StrategyConfig):
        super().__init__(config)
        self.ensemble_learner = EnsembleLearner(config.ai_ensemble)
        self.regime_detector = MarketRegimeDetector(config.ai_ensemble)
        self.confidence_threshold = config.ai_ensemble.confidence_threshold
        logger.info("AIEnsembleStrategy initialized.")

    async def analyze_market(self, df: pd.DataFrame, open_positions: List[Position]) -> Optional[Dict[str, Any]]:
        position_open = any(p.symbol == self.symbol for p in open_positions)

        # 1. Detect market regime
        regime_result = await self.regime_detector.detect_regime(self.symbol, df)
        regime = regime_result.get('regime', 'unknown')
        logger.debug("Market regime detected", regime=regime, confidence=regime_result.get('confidence'))

        # Avoid trading in uncertain or volatile regimes
        if regime in ['unknown', 'volatile']:
            return None

        # 2. Get prediction from ML ensemble
        prediction = await self.ensemble_learner.predict(df, self.symbol)
        action = prediction.get('action')
        confidence = prediction.get('confidence', 0.0)
        logger.debug("AI prediction received", action=action, confidence=confidence)

        if confidence < self.confidence_threshold:
            return None

        # 3. Generate signal based on action and regime
        if not position_open and action == 'buy' and regime == 'bull':
            logger.info("BUY signal generated by AIEnsembleStrategy", symbol=self.symbol, confidence=confidence)
            return {'action': 'BUY', 'symbol': self.symbol, 'reason': 'AI Bullish Signal'}
        
        if position_open and action == 'sell':
            logger.info("SELL signal generated by AIEnsembleStrategy", symbol=self.symbol, confidence=confidence)
            return {'action': 'SELL', 'symbol': self.symbol, 'reason': 'AI Bearish Signal'}

        return None
